// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4U1UhBqpyk0VaUg9o97Akq4DV6LkeZUU',
    appId: '1:559500818795:web:f61ee9cf8e8fcf402e742e',
    messagingSenderId: '559500818795',
    projectId: 'hf-mobile-lernzeit-tracker-v2',
    authDomain: 'hf-mobile-lernzeit-tracker-v2.firebaseapp.com',
    storageBucket: 'hf-mobile-lernzeit-tracker-v2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEUoaIm4sgXGQZKX0wCpBTxI-sQlFz10I',
    appId: '1:559500818795:android:cc92b403e9ffa49f2e742e',
    messagingSenderId: '559500818795',
    projectId: 'hf-mobile-lernzeit-tracker-v2',
    storageBucket: 'hf-mobile-lernzeit-tracker-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgb6PBRsKLnCYyIYYfOXtbKsEEJ_e4icg',
    appId: '1:559500818795:ios:569f1036cbe3070d2e742e',
    messagingSenderId: '559500818795',
    projectId: 'hf-mobile-lernzeit-tracker-v2',
    storageBucket: 'hf-mobile-lernzeit-tracker-v2.firebasestorage.app',
    iosBundleId: 'com.example.lernzeitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgb6PBRsKLnCYyIYYfOXtbKsEEJ_e4icg',
    appId: '1:559500818795:ios:569f1036cbe3070d2e742e',
    messagingSenderId: '559500818795',
    projectId: 'hf-mobile-lernzeit-tracker-v2',
    storageBucket: 'hf-mobile-lernzeit-tracker-v2.firebasestorage.app',
    iosBundleId: 'com.example.lernzeitTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4U1UhBqpyk0VaUg9o97Akq4DV6LkeZUU',
    appId: '1:559500818795:web:74299f4c13ccf41a2e742e',
    messagingSenderId: '559500818795',
    projectId: 'hf-mobile-lernzeit-tracker-v2',
    authDomain: 'hf-mobile-lernzeit-tracker-v2.firebaseapp.com',
    storageBucket: 'hf-mobile-lernzeit-tracker-v2.firebasestorage.app',
  );
}
